// Registry of every editable section: which table, what kind, and which fields to render.
// Each section appears in the admin sidebar and gets a fully-typed form with explicit fields.

export type FieldType = "text" | "textarea" | "number" | "image" | "url" | "select" | "boolean";
export type FieldDef = {
  name: string;
  label: string;
  type: FieldType;
  help?: string;
  rows?: number;
  /** Image: recommended pixel dimensions shown beneath the field. */
  dims?: string;
  /** Select: where to load options from. */
  optionsFrom?: { table: string; valueField: string; labelField: string };
};

export type SingletonSchema = {
  kind: "singleton";
  key: string; // route segment
  table: string; // db table name
  title: string;
  description: string;
  fields: FieldDef[];
};

export type ListSchema = {
  kind: "list";
  key: string;
  table: string;
  title: string;
  description: string;
  itemLabel: (row: any) => string;
  fields: FieldDef[];
};

export type SectionSchema = SingletonSchema | ListSchema;

/* Common field builders */
const t = (name: string, label: string, help?: string): FieldDef => ({
  name,
  label,
  type: "text",
  help,
});
const ta = (name: string, label: string, rows = 3): FieldDef => ({
  name,
  label,
  type: "textarea",
  rows,
});
const n = (name: string, label: string): FieldDef => ({ name, label, type: "number" });
const img = (name: string, label: string, dims = "1600 × 1200 px"): FieldDef => ({
  name,
  label,
  type: "image",
  dims,
});
const u = (name: string, label: string): FieldDef => ({ name, label, type: "url" });
const sel = (
  name: string,
  label: string,
  optionsFrom: { table: string; valueField: string; labelField: string },
  help?: string,
): FieldDef => ({ name, label, type: "select", optionsFrom, help });
const bool = (name: string, label: string, help?: string): FieldDef => ({
  name,
  label,
  type: "boolean",
  help,
});

/* ---- Schema registry ---- */
export const SCHEMAS: Record<string, SectionSchema> = {
  hero: {
    kind: "singleton",
    key: "hero",
    table: "hero",
    title: "Hero",
    description:
      "The top of the homepage — background photograph, the logo lockup and three stats. The logo mark here is also used on the loading screen.",
    fields: [
      img(
        "background_image_url",
        "Background image",
        "2400 × 1600 px (landscape, ~3:2). Max 15 MB.",
      ),
      img(
        "logo_url",
        "Logo mark",
        "The KGS logo — used in the hero AND on the loading screen. Use a WHITE / light SVG or transparent PNG — it sits on dark backgrounds. ~240 × 300 px. Leave empty to use the built-in monogram.",
      ),
      n("stat1_value", "Stat 1 — number"),
      t("stat1_suffix", "Stat 1 — suffix"),
      t("stat1_label", "Stat 1 — label"),
      n("stat2_value", "Stat 2 — number"),
      t("stat2_suffix", "Stat 2 — suffix"),
      t("stat2_label", "Stat 2 — label"),
      n("stat3_value", "Stat 3 — number"),
      t("stat3_suffix", "Stat 3 — suffix"),
      t("stat3_label", "Stat 3 — label"),
      t(
        "partners_label",
        "Material partners — heading",
        "Heading text above the scrolling brand strip below the hero.",
      ),
    ],
  },
  partners: {
    kind: "list",
    key: "partners",
    table: "partners",
    title: "Material partners strip",
    description:
      'The scrolling brand strip below the hero (Saint-Gobain, Schüco, etc.). Its heading text is the hero\'s "Material partners — heading" field.',
    itemLabel: (r) => r.name,
    fields: [
      t("name", "Partner name"),
      img("logo_url", "Logo icon", "256 × 256 px PNG/SVG, transparent background"),
      n("sort_order", "Sort order"),
    ],
  },
  features_intro: {
    kind: "singleton",
    key: "features_intro",
    table: "features_intro",
    title: "Platform — Section intro",
    description: "Eyebrow, heading and lead-in for the Platform section.",
    fields: [
      t("eyebrow", "Eyebrow"),
      ta("heading", "Heading", 2),
      ta("description", "Description", 3),
    ],
  },
  features: {
    kind: "list",
    key: "features",
    table: "features",
    title: "Platform — Feature cards",
    description: "Four capability cards. Visual kind controls which mini-UI renders.",
    itemLabel: (r) => r.title,
    fields: [
      t("tag", "Tag (e.g. 01 / Simulation)"),
      t("title", "Title"),
      ta("description", "Description", 3),
      t("visual_kind", "Visual kind", "One of: wind, bim, gauge, energy"),
      n("sort_order", "Sort order"),
    ],
  },
  statement: {
    kind: "singleton",
    key: "statement",
    table: "statement",
    title: "Architectural Statement",
    description: "Identity statement section with portrait image.",
    fields: [
      t("eyebrow", "Eyebrow"),
      ta("heading_main", "Heading — main", 2),
      ta("heading_accent", "Heading — accent (italic blue)", 2),
      img("image_url", "Portrait image", "1200 × 1500 px (4:5 portrait)"),
      ta("paragraph1", "Paragraph 1", 4),
      ta("paragraph2", "Paragraph 2", 4),
      t("meta1_key", "Meta 1 — label"),
      t("meta1_value", "Meta 1 — value"),
      t("meta2_key", "Meta 2 — label"),
      t("meta2_value", "Meta 2 — value"),
      t("meta3_key", "Meta 3 — label"),
      t("meta3_value", "Meta 3 — value"),
      t("meta4_key", "Meta 4 — label"),
      t("meta4_value", "Meta 4 — value"),
    ],
  },
  expertise_intro: {
    kind: "singleton",
    key: "expertise_intro",
    table: "expertise_intro",
    title: "Expertise — Section intro",
    description: "Header for the Expertise grid.",
    fields: [
      t("eyebrow", "Eyebrow"),
      ta("heading", "Heading", 2),
      ta("description", "Description", 3),
    ],
  },
  expertise_items: {
    kind: "list",
    key: "expertise_items",
    table: "expertise_items",
    title: "Expertise — Items",
    description:
      "Six capability cards. Each has a tile (homepage) plus a detailed body and four spec rows (expertise page).",
    itemLabel: (r) => r.title,
    fields: [
      t("number_label", "Number (e.g. 01)"),
      t("title", "Title"),
      ta("description", "Card description (homepage tile)", 3),
      ta("short_description", "Short summary (expertise page tab)", 2),
      ta("body", "Full body paragraph (expertise page detail)", 4),
      img("image_url", "Image", "1400 × 1100 px (5:4 landscape)"),
      t("spec1_key", "Spec 1 — label"),
      t("spec1_value", "Spec 1 — value"),
      t("spec2_key", "Spec 2 — label"),
      t("spec2_value", "Spec 2 — value"),
      t("spec3_key", "Spec 3 — label"),
      t("spec3_value", "Spec 3 — value"),
      t("spec4_key", "Spec 4 — label"),
      t("spec4_value", "Spec 4 — value"),
      n("sort_order", "Sort order"),
    ],
  },
  projects_intro: {
    kind: "singleton",
    key: "projects_intro",
    table: "projects_intro",
    title: "Projects — Section intro",
    description: "Heading + archive panel content.",
    fields: [
      t("eyebrow", "Eyebrow"),
      ta("heading", "Heading", 2),
      ta("description", "Description", 3),
      ta("archive_title", "Archive title", 2),
      t("archive_cta_label", "Archive CTA label"),
      u("archive_cta_link", "Archive CTA link"),
    ],
  },
  projects: {
    kind: "list",
    key: "projects",
    table: "projects",
    title: "Projects",
    description: "Projects shown on the homepage scroll and on the /projects portfolio page.",
    itemLabel: (r) => r.name,
    fields: [
      t("number_label", "Number (e.g. 01)"),
      t("name", "Project name"),
      t("location", "Location"),
      t("system_description", "System (e.g. Curtain Wall · ACP)"),
      t("year", "Year"),
      t("status", "Status (Delivered / In Progress)"),
      t("tag", "Category tag (Commercial / Mixed-Use / Residential)"),
      t("scope", "Scope (e.g. Design · Engineering · Install)"),
      t("area", "Area (e.g. 62,000 sqft)"),
      ta("full_description", "Long description (projects-page modal)", 4),
      img("image_url", "Cover image", "1600 × 1100 px (16:11 landscape)"),
      n("sort_order", "Sort order"),
    ],
  },
  process_intro: {
    kind: "singleton",
    key: "process_intro",
    table: "process_intro",
    title: "Process — Section intro",
    description: "Heading for the engineering process timeline.",
    fields: [
      t("eyebrow", "Eyebrow"),
      t("heading_main", "Heading — main"),
      t("heading_accent", "Heading — accent (italic blue)"),
    ],
  },
  process_steps: {
    kind: "list",
    key: "process_steps",
    table: "process_steps",
    title: "Process — Steps",
    description: "Six timeline steps used on the homepage and the /process page.",
    itemLabel: (r) => r.title,
    fields: [
      t("number_label", "Number"),
      t("title", "Title"),
      ta("description", "Description", 3),
      n("sort_order", "Sort order"),
      t("weeks", "Time range (e.g. Wk 1–2)"),
      t("deliverable1", "Deliverable 1"),
      t("deliverable2", "Deliverable 2"),
      t("deliverable3", "Deliverable 3"),
    ],
  },
  manufacturing: {
    kind: "singleton",
    key: "manufacturing",
    table: "manufacturing",
    title: "Manufacturing",
    description: "Factory section — heading, capabilities, one feature image and four stats.",
    fields: [
      t("eyebrow", "Eyebrow"),
      ta("heading", "Heading", 2),
      ta("description", "Description", 3),
      img("image_url", "Feature image", "2400 × 1400 px (wide landscape, ~16:9 to 21:9)"),
      t("capability1", "Capability 1"),
      t("capability2", "Capability 2"),
      t("capability3", "Capability 3"),
      t("capability4", "Capability 4"),
      n("stat1_value", "Stat 1 — value"),
      n("stat1_decimals", "Stat 1 — decimals"),
      t("stat1_suffix", "Stat 1 — suffix"),
      t("stat1_label", "Stat 1 — label"),
      n("stat2_value", "Stat 2 — value"),
      n("stat2_decimals", "Stat 2 — decimals"),
      t("stat2_suffix", "Stat 2 — suffix"),
      t("stat2_label", "Stat 2 — label"),
      n("stat3_value", "Stat 3 — value"),
      n("stat3_decimals", "Stat 3 — decimals"),
      t("stat3_suffix", "Stat 3 — suffix"),
      t("stat3_label", "Stat 3 — label"),
      n("stat4_value", "Stat 4 — value"),
      n("stat4_decimals", "Stat 4 — decimals"),
      t("stat4_suffix", "Stat 4 — suffix"),
      t("stat4_label", "Stat 4 — label"),
    ],
  },
  why_intro: {
    kind: "singleton",
    key: "why_intro",
    table: "why_intro",
    title: "Why KGS — Section intro",
    description: "Header for the three principles.",
    fields: [t("eyebrow", "Eyebrow"), ta("heading", "Heading", 2)],
  },
  why_cards: {
    kind: "list",
    key: "why_cards",
    table: "why_cards",
    title: "Why KGS — Cards",
    description: "Three principle cards.",
    itemLabel: (r) => r.title,
    fields: [
      t("number_label", "Number"),
      t("title", "Title"),
      ta("description", "Description", 4),
      n("sort_order", "Sort order"),
    ],
  },
  contact: {
    kind: "singleton",
    key: "contact",
    table: "contact",
    title: "Contact — Consultation",
    description: "Consultation form section heading + contact details.",
    fields: [
      t("eyebrow", "Eyebrow"),
      ta("heading", "Heading", 2),
      ta("description", "Description", 3),
      t("email", "Email"),
      t("phone", "Phone"),
      t("office_address", "Office address"),
      t("factory_address", "Factory address"),
    ],
  },

  /* ============ Projects sub-page ============ */
  projects_page: {
    kind: "singleton",
    key: "projects_page",
    table: "projects_page",
    title: "Projects page — Hero & frame",
    description: "Header, stats strip, modal blurb and CTA for the /projects page.",
    fields: [
      t("crumb", "Breadcrumb label"),
      t("hero_eyebrow", "Hero eyebrow"),
      t("hero_title", "Hero title"),
      t("hero_highlight", "Hero highlight (shimmer line)"),
      ta("hero_subtitle", "Hero subtitle", 3),
      t("stat1_value", "Stat 1 — value"),
      t("stat1_label", "Stat 1 — label"),
      t("stat2_value", "Stat 2 — value"),
      t("stat2_label", "Stat 2 — label"),
      t("stat3_value", "Stat 3 — value"),
      t("stat3_label", "Stat 3 — label"),
      t("stat4_value", "Stat 4 — value"),
      t("stat4_label", "Stat 4 — label"),
      ta("modal_blurb", "Project modal default blurb", 3),
      t("cta_title", "CTA — title"),
      ta("cta_copy", "CTA — copy", 3),
    ],
  },

  /* ============ Process sub-page ============ */
  process_page: {
    kind: "singleton",
    key: "process_page",
    table: "process_page",
    title: "Process page — Hero & frame",
    description: "Header, section headings and CTA for the /process page.",
    fields: [
      t("crumb", "Breadcrumb label"),
      t("hero_eyebrow", "Hero eyebrow"),
      t("hero_title", "Hero title"),
      t("hero_highlight", "Hero highlight"),
      ta("hero_subtitle", "Hero subtitle", 3),
      t("timeline_eyebrow", "Timeline — eyebrow"),
      ta("timeline_heading", "Timeline — heading", 2),
      t("deliverables_eyebrow", "Deliverables — eyebrow"),
      ta("deliverables_heading", "Deliverables — heading", 2),
      t("cta_title", "CTA — title"),
      ta("cta_copy", "CTA — copy", 3),
    ],
  },
  process_principles: {
    kind: "list",
    key: "process_principles",
    table: "process_principles",
    title: "Process page — Principles bar",
    description: "Four short principles shown above the timeline.",
    itemLabel: (r) => r.key,
    fields: [t("key", "Label"), ta("value", "Value", 2), n("sort_order", "Sort order")],
  },

  /* ============ Expertise sub-page ============ */
  expertise_page: {
    kind: "singleton",
    key: "expertise_page",
    table: "expertise_page",
    title: "Expertise page — Hero & frame",
    description: "Header, section intros and CTA for the /expertise page.",
    fields: [
      t("crumb", "Breadcrumb label"),
      t("hero_eyebrow", "Hero eyebrow"),
      t("hero_title", "Hero title"),
      t("hero_highlight", "Hero highlight"),
      ta("hero_subtitle", "Hero subtitle", 3),
      t("tabs_eyebrow", "Tabs — eyebrow"),
      ta("tabs_heading", "Tabs — heading line 1", 2),
      t("tabs_heading_accent", "Tabs — heading line 2 (italic blue)"),
      t("matrix_eyebrow", "Matrix — eyebrow"),
      ta("matrix_heading", "Matrix — heading", 2),
      t("cta_title", "CTA — title"),
      ta("cta_copy", "CTA — copy", 3),
    ],
  },
  expertise_compare: {
    kind: "list",
    key: "expertise_compare",
    table: "expertise_compare",
    title: "Expertise page — Comparison matrix",
    description: "Rows in the specification matrix at the bottom of the page.",
    itemLabel: (r) => r.capability,
    fields: [
      t("capability", "Capability"),
      t("glass", "Glass"),
      t("tolerance", "Tolerance"),
      t("use_case", "Use case"),
      n("sort_order", "Sort order"),
    ],
  },

  /* ============ About sub-page ============ */
  about_page: {
    kind: "singleton",
    key: "about_page",
    table: "about_page",
    title: "About page — Hero, philosophy, stats & sections",
    description: "Every heading and copy block on the /about page.",
    fields: [
      t("crumb", "Breadcrumb label"),
      t("hero_eyebrow", "Hero eyebrow"),
      t("hero_title", "Hero title"),
      t("hero_highlight", "Hero highlight"),
      ta("hero_subtitle", "Hero subtitle", 3),
      t("philosophy_eyebrow", "Philosophy — eyebrow"),
      ta("philosophy_heading", "Philosophy — heading", 2),
      ta("paragraph1", "Philosophy — paragraph 1", 4),
      ta("paragraph2", "Philosophy — paragraph 2", 4),
      ta("paragraph3", "Philosophy — paragraph 3", 4),
      img("philosophy_image_url", "Philosophy — portrait image", "1200 × 1500 px (4:5 portrait)"),
      n("stat1_value", "Stat 1 — number"),
      t("stat1_suffix", "Stat 1 — suffix"),
      t("stat1_label", "Stat 1 — label"),
      n("stat2_value", "Stat 2 — number"),
      t("stat2_suffix", "Stat 2 — suffix"),
      t("stat2_label", "Stat 2 — label"),
      n("stat3_value", "Stat 3 — number"),
      t("stat3_suffix", "Stat 3 — suffix"),
      t("stat3_label", "Stat 3 — label"),
      n("stat4_value", "Stat 4 — number"),
      t("stat4_suffix", "Stat 4 — suffix"),
      t("stat4_label", "Stat 4 — label"),
      t("timeline_eyebrow", "Timeline — eyebrow"),
      ta("timeline_heading", "Timeline — heading", 2),
      t("leadership_eyebrow", "Leadership — eyebrow"),
      ta("leadership_heading", "Leadership — heading", 2),
      ta("leadership_intro", "Leadership — intro", 3),
      img("factory_image_url", "Factory image", "1600 × 2000 px (4:5 portrait)"),
      t("factory_label", "Factory — small label"),
      t("factory_name", "Factory — name"),
      t("certifications_eyebrow", "Certifications — eyebrow"),
      ta("certifications_heading", "Certifications — heading", 2),
      ta("certifications_intro", "Certifications — intro", 3),
      t("cta_title", "CTA — title"),
      ta("cta_copy", "CTA — copy", 3),
    ],
  },
  about_timeline: {
    kind: "list",
    key: "about_timeline",
    table: "about_timeline",
    title: "About — Timeline",
    description: "Milestones shown on the /about timeline.",
    itemLabel: (r) => `${r.year} · ${r.title}`,
    fields: [
      t("year", "Year"),
      t("title", "Title"),
      ta("description", "Description", 3),
      n("sort_order", "Sort order"),
    ],
  },
  about_leadership: {
    kind: "list",
    key: "about_leadership",
    table: "about_leadership",
    title: "About — Leadership",
    description: "Leadership cards. Image optional — initials fallback otherwise.",
    itemLabel: (r) => r.name,
    fields: [
      t("name", "Name"),
      t("role", "Role"),
      ta("bio", "Bio", 3),
      img("image_url", "Portrait (optional)", "640 × 640 px (1:1 square)"),
      n("sort_order", "Sort order"),
    ],
  },
  about_certifications: {
    kind: "list",
    key: "about_certifications",
    table: "about_certifications",
    title: "About — Certifications",
    description: "Certification labels shown next to the factory image.",
    itemLabel: (r) => r.label,
    fields: [t("label", "Label"), n("sort_order", "Sort order")],
  },
  footer: {
    kind: "singleton",
    key: "footer",
    table: "footer",
    title: "Footer",
    description:
      "The closing wordmark at the very bottom of the homepage, plus the social links. Renders as: line 1, then accent + rest.",
    fields: [
      t("brand_line1", "Brand — line 1", "e.g. 'Kolkata'."),
      t("brand_line2_accent", "Brand — line 2 accent (italic blue)", "e.g. 'Glazing'."),
      t("brand_line2_rest", "Brand — line 2 rest", "e.g. 'Services'."),
      {
        name: "instagram_url",
        label: "Instagram page",
        type: "url",
        help: "Full link, e.g. https://www.instagram.com/kolkataglazing. Leave empty to hide the icon.",
      },
      {
        name: "facebook_url",
        label: "Facebook page",
        type: "url",
        help: "Full link, e.g. https://www.facebook.com/kolkataglazing. Leave empty to hide the icon.",
      },
    ],
  },
  clients_page: {
    kind: "singleton",
    key: "clients_page",
    table: "clients_page",
    title: "Clients page",
    description: "Hero, stats and CTA for the /clients page.",
    fields: [
      t("crumb", "Breadcrumb"),
      t("hero_eyebrow", "Hero eyebrow"),
      ta("hero_title", "Hero title", 2),
      t("hero_highlight", "Hero highlight (italic accent)"),
      ta("hero_subtitle", "Hero subtitle", 3),
      t("stat1_value", "Stat 1 — value"),
      t("stat1_label", "Stat 1 — label"),
      t("stat2_value", "Stat 2 — value"),
      t("stat2_label", "Stat 2 — label"),
      t("stat3_value", "Stat 3 — value"),
      t("stat3_label", "Stat 3 — label"),
      ta("cta_title", "CTA title", 2),
      ta("cta_copy", "CTA copy", 3),
    ],
  },
  clients: {
    kind: "list",
    key: "clients",
    table: "clients",
    title: "Clients — Companies",
    description: "Each developer/client showcased on the /clients page.",
    itemLabel: (r) => r.name,
    fields: [
      t("name", "Company name"),
      t(
        "slug",
        "Slug (lowercase, used in /clients/<slug>)",
        "Used for the dedicated client detail page URL.",
      ),
      img("logo_url", "Logo", "400 × 400 px, transparent PNG/SVG"),
      img("hero_image_url", "Detail-page hero image", "2400 × 1200 px (cinematic banner)"),
      t("tagline", "Tagline (short one-liner)"),
      ta("description", "Description", 4),
      ta("about_long", "Long-form about (detail page)", 6),
      t("sector", "Sector (e.g. Real Estate · Hospitality)"),
      t("city", "Headquartered in"),
      t("established_year", "Established (year)"),
      t("partnership_since", "Partner since (year)"),
      u("website", "Website URL"),
      bool("featured", "Featured client", "Pin to the top of the /clients index."),
      n("sort_order", "Sort order"),
    ],
  },
  client_projects: {
    kind: "list",
    key: "client_projects",
    table: "client_projects",
    title: "Clients — Projects",
    description: "Projects delivered for a client. Pick the parent client by its UUID.",
    itemLabel: (r) => r.name,
    fields: [
      sel(
        "client_id",
        "Client",
        { table: "clients", valueField: "id", labelField: "name" },
        "Pick the parent client. Manage clients in 'Clients — Companies'.",
      ),
      t("name", "Project name"),
      t("slug", "Slug (used in detail-page anchors)"),
      t("location", "Location"),
      t("year", "Year"),
      t("completion_date", "Completion date (e.g. Mar 2024)"),
      t("duration", "Duration (e.g. 14 months)"),
      t("status", "Status (Delivered / In Progress)"),
      t("system_description", "System (e.g. Curtain Wall · ACP)"),
      t("scope", "Scope (e.g. Design · Engineering · Install)"),
      t("area", "Area (e.g. 62,000 sqft)"),
      t("sqft_value", "Façade area (numeric, e.g. 62000)"),
      ta("kgs_role", "KGS role on this project", 3),
      t("valuation", "Project / envelope valuation"),
      t("fee", "KGS fee charged"),
      ta("description", "Full description", 4),
      img("image_url", "Cover image", "1600 × 1100 px (16:11 landscape)"),
      img("hero_image_url", "Detail-page hero (optional)", "2400 × 1400 px (cinematic banner)"),
      ta("gallery_urls", "Gallery image URLs", 5),
      ta("testimonial_quote", "Testimonial — quote", 4),
      t("testimonial_author", "Testimonial — author"),
      t("testimonial_role", "Testimonial — role/title"),
      ta("awards", "Awards & recognition", 2),
      n("sort_order", "Sort order"),
    ],
  },
};

/* Sidebar grouping for the admin UI */
export const SIDEBAR_GROUPS: { label: string; items: string[] }[] = [
  { label: "Home — Hero", items: ["hero", "partners"] },
  { label: "Home — Platform", items: ["features_intro", "features"] },
  { label: "Home — Statement", items: ["statement"] },
  { label: "Home — Expertise", items: ["expertise_intro", "expertise_items"] },
  { label: "Home — Projects", items: ["projects_intro", "projects"] },
  { label: "Home — Process", items: ["process_intro", "process_steps"] },
  { label: "Home — Manufacturing", items: ["manufacturing"] },
  { label: "Home — Why KGS", items: ["why_intro", "why_cards"] },
  { label: "Home — Contact", items: ["contact"] },
  { label: "Projects page", items: ["projects_page"] },
  { label: "Process page", items: ["process_page", "process_principles"] },
  { label: "Expertise page", items: ["expertise_page", "expertise_compare"] },
  {
    label: "About page",
    items: ["about_page", "about_timeline", "about_leadership", "about_certifications"],
  },
  { label: "Clients page", items: ["clients_page", "clients", "client_projects"] },
  { label: "Global — Footer", items: ["footer"] },
];
